# Left Rear leg — IDs 1, 2, 3
hexapod_servo:
  port: "/dev/ttyUSB0"
  baud_rate: 1000000
  servos:
    coxa_joint_LR:  { id: 1,  type: "AX-18A", ticks: 1024, center: 512, max_radians: 5.236, sign: 1,  offset: 0.00614 }
    femur_joint_LR: { id: 2,  type: "AX-18A", ticks: 1024, center: 512, max_radians: 5.236, sign: 1,  offset: 0.00614 }
    tibia_joint_LR: { id: 3,  type: "AX-18A", ticks: 1024, center: 512, max_radians: 5.236, sign: -1, offset: 0.00614 }

hexapod_ik:
  coxa_length: 0.044
  femur_length: 0.0545
  tibia_length: 0.1019
  joint_names: ["coxa_joint_LR", "femur_joint_LR", "tibia_joint_LR"]
