/gait_node:
  ros__parameters:
    cycle_length: 50
    lift_height: 0.0375
    velocity_scaling: 0.15
    low_pass_alpha: 0.05

/ik_node:
  ros__parameters:
    number_of_legs: 6
    number_of_leg_segments: 3
    coxa_length: 0.044
    femur_length: 0.0545
    tibia_length: 0.1019
    tarsus_length: 0.0
    standing_body_height: 0.02
    body_max_roll: 0.1396
    body_max_pitch: 0.1396
    body_max_yaw: 0.3491
    init_coxa_angle: [-0.4581, 0.0, 0.4581, -0.4581, 0.0, 0.4581]
    coxa_to_center_x: [-0.065, 0.0, 0.065, -0.065, 0.0, 0.065]
    coxa_to_center_y: [0.0325, 0.0625, 0.0325, 0.0325, 0.0625, 0.0325]
    init_foot_pos_x: [-0.04190685, 0.0, 0.04190685, -0.04190685, 0.0, 0.04190685]
    init_foot_pos_y: [0.084978692, 0.09475, 0.084978692, 0.084978692, 0.09475, 0.084978692]
    init_foot_pos_z: [0.07, 0.07, 0.07, 0.07, 0.07, 0.07]

/servo_node:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baud_rate: 1000000
    protocol_version: 1.0
    servo_count: 18
    torque_enable_reg: 24
    present_position_reg: 36
    goal_position_reg: 30

/control_node:
  ros__parameters:
    master_loop_rate: 500
    interpolation_loop_rate: 1000
    velocity_division: 0.033
